### ISSUE TITLE
New test for generic move

### ISSUE THREAD

**Issue by dsarrut** [OpenGATE/GateBenchmarks#48]
(From Matthew) 
https://github.com/mxh1092/GATE_Movement_Benchmark.

The macros induce movement of both a source and the detector volumes. I’ve written a python script which analyses the output of the simulation. This script compares the position where particles are generated to the source placements file and also the positions of the detected particles to the detector placements file. The script then returns a True or False if the benchmark is passed. There’s also a script for visualisation.

**Comment by tbaudier** [comment]
Done with https://github.com/OpenGATE/GateBenchmarks/pull/49
